name: Build and deploy .NET application to container app eunomia-dev-webapp
on:
  push:
    branches:
    - main
env:
  CONTAINER_APP_CONTAINER_NAME: eunomiawebapp
  CONTAINER_APP_NAME: eunomia-dev-webapp
  CONTAINER_APP_RESOURCE_GROUP_NAME: eunomia-dev-rg
  CONTAINER_REGISTRY_LOGIN_SERVER: eunomiacontainerreg.azurecr.io
  DOCKER_FILE_PATH: Dockerfile
  PROJECT_NAME_FOR_DOCKER: eunomiawebapp
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.eunomiacontainerreg_USERNAME_C221 }}
        password: ${{ secrets.eunomiacontainerreg_PASSWORD_C221 }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.eunomia_dev_webapp_SPN }}
    - name: Deploy to containerapp
      uses: azure/CLI@v1
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.eunomiacontainerreg_USERNAME_C221 }} --password ${{ secrets.eunomiacontainerreg_PASSWORD_C221 }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: logout
      run: >
        az logout
